# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yunus\OneDrive\Desktop\pythonogreniyorum\ATM-Project\atmproject - Version-2\atm_proje_file\admin_choice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import os
__location__ = os.path.realpath(
        os.path.join(os.getcwd(), os.path.dirname(__file__)))
class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 359)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.return2_button = QtWidgets.QPushButton(self.centralwidget)
        self.return2_button.setGeometry(QtCore.QRect(310, 240, 101, 41))
        self.return2_button.setStyleSheet("background-color: rgb(254, 204, 102);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(__location__, "reply.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(os.path.join(__location__, "reply.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.return2_button.setIcon(icon)
        self.return2_button.setIconSize(QtCore.QSize(30, 30))
        self.return2_button.setObjectName("return2_button")
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(90, 40, 141, 51))
        self.btn_register.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(230, 230, 230);")
        self.btn_register.setObjectName("btn_register")
        self.btn_activities = QtWidgets.QPushButton(self.centralwidget)
        self.btn_activities.setGeometry(QtCore.QRect(90, 140, 141, 51))
        self.btn_activities.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(230, 230, 230);")
        self.btn_activities.setObjectName("btn_activities")
        self.btn_change = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change.setGeometry(QtCore.QRect(90, 240, 141, 51))
        self.btn_change.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(230, 230, 230);")
        self.btn_change.setObjectName("btn_change")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 30, 71, 81))
        self.pushButton_3.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(__location__, "debit-card.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 130, 71, 81))
        self.pushButton_4.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 230, 71, 81))
        self.pushButton_5.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.return2_button.setText(_translate("MainWindow", "RETURN MENU"))
        self.btn_register.setText(_translate("MainWindow", "Customer Register"))
        self.btn_activities.setText(_translate("MainWindow", "See Daily Activities"))
        self.btn_change.setText(_translate("MainWindow", "Change customer Details"))
