# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import os
__location__ = os.path.realpath(
        os.path.join(os.getcwd(), os.path.dirname(__file__)))
class Ui_loginAdmin(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(486, 320)
        self.lineEditUser = QtWidgets.QLineEdit(Login)
        self.lineEditUser.setGeometry(QtCore.QRect(200, 60, 201, 31))
        self.lineEditUser.setObjectName("lineEditUser")
        self.lineEditPassword = QtWidgets.QLineEdit(Login)
        self.lineEditPassword.setGeometry(QtCore.QRect(200, 130, 201, 31))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonLogin = QtWidgets.QPushButton(Login)
        self.pushButtonLogin.setGeometry(QtCore.QRect(150, 200, 181, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButtonLogin.setObjectName("pushButtonLogin")

        self.pushButtonLogin2 = QtWidgets.QPushButton(Login)
        self.pushButtonLogin2.setGeometry(QtCore.QRect(150, 260, 181, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonLogin2.setFont(font)
        self.pushButtonLogin2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButtonLogin2.setObjectName("pushButtonLogin2")

        self.labelErrorMessage = QtWidgets.QLabel(Login)
        self.labelErrorMessage.setGeometry(QtCore.QRect(70, 270, 351, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelErrorMessage.setFont(font)
        self.labelErrorMessage.setObjectName("labelErrorMessage")
        self.labelHead = QtWidgets.QLabel(Login)
        self.labelHead.setGeometry(QtCore.QRect(90, 0, 271, 41))
        self.labelHead.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelHead.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.labelHead.setObjectName("labelHead")
        self.labelUserName = QtWidgets.QLabel(Login)
        self.labelUserName.setGeometry(QtCore.QRect(20, 60, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelUserName.setFont(font)
        self.labelUserName.setObjectName("labelUserName")
        self.labelUserPassword = QtWidgets.QLabel(Login)
        self.labelUserPassword.setGeometry(QtCore.QRect(20, 140, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelUserPassword.setFont(font)
        self.labelUserPassword.setObjectName("labelUserPassword")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.pushButtonLogin.setText(_translate("Login", "Login"))
        self.labelErrorMessage.setText(_translate("Login", "TextLabel"))
        self.labelHead.setText(_translate("Login", "       Bank Login Page"))
        self.labelUserName.setText(_translate("Login", "Username:"))
        self.labelUserPassword.setText(_translate("Login", "User Password :"))
        self.pushButtonLogin2.setText(_translate("Login", "Return"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_loginAdmin()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
