# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yunus\OneDrive\Desktop\pythonogreniyorum\ATM-Project\atmproject - Version-2\atm_proje_file\See_bank_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 300)
        MainWindow.setMinimumSize(QtCore.QSize(512, 300))
        MainWindow.setMaximumSize(QtCore.QSize(512, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_total_money = QtWidgets.QLabel(self.centralwidget)
        self.lbl_total_money.setGeometry(QtCore.QRect(30, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_total_money.setFont(font)
        self.lbl_total_money.setStyleSheet("font: 14pt \".AppleSystemUIFont\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(254, 204, 102);")
        self.lbl_total_money.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_money.setObjectName("lbl_total_money")
        self.lbl_total_money_show = QtWidgets.QLabel(self.centralwidget)
        self.lbl_total_money_show.setGeometry(QtCore.QRect(290, 20, 161, 31))
        self.lbl_total_money_show.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lbl_total_money_show.setText("")
        self.lbl_total_money_show.setObjectName("lbl_total_money_show")
        self.lbl_total_withdraw = QtWidgets.QLabel(self.centralwidget)
        self.lbl_total_withdraw.setGeometry(QtCore.QRect(30, 80, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_total_withdraw.setFont(font)
        self.lbl_total_withdraw.setStyleSheet("font: 14pt \".AppleSystemUIFont\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(254, 204, 102);")
        self.lbl_total_withdraw.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_withdraw.setObjectName("lbl_total_withdraw")
        self.lbl_total_withdraw_show = QtWidgets.QLabel(self.centralwidget)
        self.lbl_total_withdraw_show.setGeometry(QtCore.QRect(290, 80, 161, 31))
        self.lbl_total_withdraw_show.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lbl_total_withdraw_show.setText("")
        self.lbl_total_withdraw_show.setObjectName("lbl_total_withdraw_show")
        self.lbl_total_insert = QtWidgets.QLabel(self.centralwidget)
        self.lbl_total_insert.setGeometry(QtCore.QRect(30, 140, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_total_insert.setFont(font)
        self.lbl_total_insert.setStyleSheet("font: 14pt \".AppleSystemUIFont\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(254, 204, 102);")
        self.lbl_total_insert.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_insert.setObjectName("lbl_total_insert")
        self.lbl_total_insert_show = QtWidgets.QLabel(self.centralwidget)
        self.lbl_total_insert_show.setGeometry(QtCore.QRect(290, 140, 161, 31))
        self.lbl_total_insert_show.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lbl_total_insert_show.setText("")
        self.lbl_total_insert_show.setObjectName("lbl_total_insert_show")
        self.return2_button = QtWidgets.QPushButton(self.centralwidget)
        self.return2_button.setGeometry(QtCore.QRect(200, 200, 101, 41))
        self.return2_button.setStyleSheet("background-color: rgb(254, 204, 102);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\yunus\\OneDrive\\Desktop\\pythonogreniyorum\\ATM-Project\\atmproject - Version-2\\atm_proje_file\\../pythonogreniyorum/ATM-Project/atmproject/gümüst/icons/reply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\yunus\\OneDrive\\Desktop\\pythonogreniyorum\\ATM-Project\\atmproject - Version-2\\atm_proje_file\\../pythonogreniyorum/ATM-Project/gümüst/icons/icns/reply.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.return2_button.setIcon(icon)
        self.return2_button.setIconSize(QtCore.QSize(50, 50))
        self.return2_button.setObjectName("return2_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_total_money.setText(_translate("MainWindow", "Total Money in bank"))
        self.lbl_total_withdraw.setText(_translate("MainWindow", "Daily Total Withdraw"))
        self.lbl_total_insert.setText(_translate("MainWindow", "Daily Total Insert"))
        self.return2_button.setText(_translate("MainWindow", "RETURN MENU"))
