# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yunus\OneDrive\Desktop\atmproject\deneme\withdraw.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_withdrawScreen(object):
    def setupUi(self, withdrawScreen):
        withdrawScreen.setObjectName("withdrawScreen")
        withdrawScreen.resize(559, 483)
        withdrawScreen.setStyleSheet("background-color: rgb(127, 127, 127);")
        self.centralwidget = QtWidgets.QWidget(withdrawScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.return3_button = QtWidgets.QPushButton(self.centralwidget)
        self.return3_button.setGeometry(QtCore.QRect(220, 350, 171, 51))
        self.return3_button.setStyleSheet("background-color: rgb(254, 204, 102);")
        icon = QtGui.QIcon()
        filelog = os.getcwd()
        icon.addPixmap(QtGui.QPixmap(f"{filelog}\\atmproject\\atm_proje_file\\icns\\reply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(f"{filelog}\\atmproject\\atm_proje_file\\icns\\reply.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.return3_button.setIcon(icon)
        self.return3_button.setIconSize(QtCore.QSize(50, 50))
        self.return3_button.setObjectName("return3_button")
        self.witdraw_label = QtWidgets.QLabel(self.centralwidget)
        self.witdraw_label.setGeometry(QtCore.QRect(20, 90, 151, 31))
        self.witdraw_label.setStyleSheet("background-color: rgb(254, 204, 102);")
        self.witdraw_label.setObjectName("witdraw_label")
        self.witdraw_label.setAlignment(QtCore.Qt.AlignCenter)
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(420, 20, 113, 32))
        self.exit_button.setStyleSheet("background-color: rgb(127, 127, 127);")
        self.exit_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(f"{filelog}\\atmproject\\atm_proje_file\\icns\\Küçük indir (4) .png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon1)
        self.exit_button.setIconSize(QtCore.QSize(100, 50))
        self.exit_button.setObjectName("exit_button")
        self.withdraw_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.withdraw_edit.setGeometry(QtCore.QRect(220, 90, 171, 31))
        self.withdraw_edit.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.withdraw_edit.setText("")
        self.withdraw_edit.setObjectName("withdraw_edit")
        self.withdraw_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.avaible_label = QtWidgets.QLabel(self.centralwidget)
        self.avaible_label.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.avaible_label.setStyleSheet("font: 10pt \".AppleSystemUIFont\";\n"
"background-color: rgb(254, 204, 102);")
        self.avaible_label.setObjectName("avaible_label")
        self.avaible_label.setAlignment(QtCore.Qt.AlignCenter)
        self.enter_button = QtWidgets.QPushButton(self.centralwidget)
        self.enter_button.setGeometry(QtCore.QRect(420, 90, 113, 32))
        self.enter_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(f"{filelog}\\atmproject\\atm_proje_file\\icns\\Küçük images (1) .png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(f"{filelog}\\atmproject\\atm_proje_file\\icns\\Küçük images (1) .png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.enter_button.setIcon(icon2)
        self.enter_button.setIconSize(QtCore.QSize(100, 70))
        self.enter_button.setObjectName("enter_button")
        self.balance3_label = QtWidgets.QLabel(self.centralwidget)
        self.balance3_label.setGeometry(QtCore.QRect(220, 19, 171, 31))
        self.balance3_label.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.balance3_label.setText("")
        self.balance3_label.setObjectName("balance3_label")
        self.balance3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.messsage2_button = QtWidgets.QPushButton(self.centralwidget)
        self.messsage2_button.setGeometry(QtCore.QRect(171, 150, 250, 175))
        self.messsage2_button.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.messsage2_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(f"{filelog}\\atmproject\\atm_proje_file\\icns\\atm-machine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.messsage2_button.setIcon(icon3)
        self.messsage2_button.setIconSize(QtCore.QSize(100, 100))
        self.messsage2_button.setObjectName("messsage2_button")
        withdrawScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(withdrawScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 559, 24))
        self.menubar.setObjectName("menubar")
        withdrawScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(withdrawScreen)
        self.statusbar.setObjectName("statusbar")
        withdrawScreen.setStatusBar(self.statusbar)

        self.retranslateUi(withdrawScreen)
        QtCore.QMetaObject.connectSlotsByName(withdrawScreen)

    def retranslateUi(self, withdrawScreen):
        _translate = QtCore.QCoreApplication.translate
        withdrawScreen.setWindowTitle(_translate("withdrawScreen", "withdraw"))
        self.return3_button.setText(_translate("withdrawScreen", "RETURN MENU"))
        self.witdraw_label.setText(_translate("withdrawScreen", "WITHDRAW"))
        self.avaible_label.setText(_translate("withdrawScreen", "AVAIBLE BALANCE"))
